name: "Update blog post on kimmohito/README.md"
on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch :
jobs:
  update-readme-with-blog:
    name: "Update blog post on kimmohito/README.md"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "Update blog post on kimmohito/README.md"
          feed_list: "" 
          # feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
