name: Update Readme with latest about-me.yml

on:
  push:
    brances:
      - main

jobs:
  Update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - run: sed -i '/<!-- ABOUTME:START -->/,/<!-- ABOUTME:END -->/d' README.md
      - run: echo '<!-- ABOUTME:START -->' >> README.md
      - run: cat about-me.yml >> README.md
      - run: echo '<!-- ABOUTME:END -->' >> README.md

      - name: push
        uses: actions-x/commit@v2
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        with:
            name: GitHub Actions Autocommitter
            files: ./README.md
            message: '[GITOPS] updated README with latest changes'
